### ISSUE TITLE
hw0 README 說明疑似有誤

### ISSUE THREAD

**Issue by xdavidwu** [compiler-f20/discussion#10]
README.md:

```markdown
在這次作業中你必須透過修改 Makefile 檔案，將其資料修改成正確的個人資訊並呼叫 `GNU Make` 來更新專案目錄下 README.md 的內容。別擔心，每位同學的作業專案 (Repository) 只有自己跟助教能夠存取。
```

這裡說要修改 `Makefile` , 實際上要修改的是 `student_info.ini`

```markdown
當你看到這裏時，比起最開始收到作業時的模樣，這個專案的 `Makefile` 以及 `README.md` 已經被你改動過了。接下來要將這些改動過的程式碼加入到新版本之中，納入 Git 的控管範圍內，從此成為歷史文件，跟中英聯合聲明一樣。

首先使用 `git status` 看一下當前狀態

```Shell
$ git status

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
    (use "git add <file>..." to update what will be committed)
    (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   Makefile
    modified:   README.md
```

這裡說明應該有誤, 有修改的應該是 `student_info.ini` 而不是 `Makefile`, 底下的 `git add` 跟 `git status` 倒是對的

**Comment by xdavidwu** [comment]
另外還有 `src/update-info.py` 會讀取 `res/tmpl_readme.md` 作為模板, 但 `res/tmpl_readme.md` 卻和原本 `README.md` 不符, 造成執行後在說明部份有預期外的變更

**Comment by ran-ablaze** [comment]
@xdavidwu 
感謝你的提醒。

不過因為在hw0中我們只是為了確認大家的環境安裝正確並做一些簡單的練習，這部分並不影響hw0的繳交，也不會再另外發patch給各位。

不過助教這邊對hw0的模板有做了修改，若是在這之後才開repo的同學收到的就會是正確的版本。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji :+1:，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
