### ISSUE TITLE
無法安裝docker

### ISSUE THREAD

**Issue by yuyi-lin** [compiler-f20/discussion#11]
![image](https://user-images.githubusercontent.com/55355174/93706757-3ac87480-fb5c-11ea-9225-c2f12c871127.png)
用VMware workstation安裝 ubuntu後, 照著說明文件裡的教學想在Ubuntu 下安裝 Docker,但是卻無法安裝

**Comment by 5fe6eb50c7aa19f9** [comment]
這是教學文的哪一步驟?

**Comment by yuyi-lin** [comment]
![image](https://user-images.githubusercontent.com/55355174/93706875-2042cb00-fb5d-11ea-9bb0-186bc84981f4.png)
apt-cache policy docker-ce的output就不一樣了

**Comment by 5fe6eb50c7aa19f9** [comment]
@yuyi-lin
你在apt-cache policy docker-ce前就出現錯誤訊息了，
你可能要找出最開始的錯誤在哪。

**Comment by 5fe6eb50c7aa19f9** [comment]
@yuyi-lin
參考看看這個，
https://blog.csdn.net/yz1988computer/article/details/81675553

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
