### ISSUE TITLE
在 Scientific Notations 前有 0 的情況判斷

### ISSUE THREAD

**Issue by kaiiiz** [compiler-f20/discussion#15]
助教你們好：

想請問以下情況 (出現在 11_pseudocomment.p)

```
00123E4
```

應該被判斷為 

```
<oct_integer: 00>
<scientific: 123E4>
```

還是

```
<oct_integer: 00123>
<id: E4>
```

呢？(答案目前是下面那種)

以 spec 來看：

> the coefficient a is any real number, called the significand, a decimal integer or floating-point number.

似乎上面的情況也沒有違反這個要求？

因為 float 有特別規定說 `009.1` 要切成 `00` 與 `9.1` 所以想確認一下在 Scientific Notations 中前方有多餘的 0 的情況，感謝！

**Comment by chrisPyr** [comment]
同學你好：
答案是下面那個，因為在做match的時候會從第一個字元讀到能到match到最長的pattern為止。

009.1之所以切成00 和9.1 是因為009 不是octal number 所以才會切到00停止，並不是有開頭有00就一定要把00切開。
---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by kaiiiz** [comment]
ok，我了解了，感謝助教！
