### ISSUE TITLE
9_float.p 測資問題

### ISSUE THREAD

**Issue by kaiiiz** [compiler-f20/discussion#16]
助教你們好：

想請問在 `advance_cases/test_cases/9_float.p` 中第 7 行

```
00123.123
```

根據 spec：

> Note that 009.1 is a valid input in P (whether 009.1 is a valid syntax should not be the lexer's concern) because the input would be recognized as two seperate tokens: 00 (an octal integer constant) and 9.1 (a floating-point constant).

所以答案應該是：

```
<oct_integer: 00>
<float: 123.123>
```

嗎？我在 sample_solutions 中看到的是：

```
Error at line 7: bad character "."
```

考慮八進制與浮點數混用的情況，想確認一下，感謝！

**Comment by chrisPyr** [comment]
@kaiiiz 
請同學再多理解spec的內容及pattern matching的方式。

關於為什麼009.1會切成00 及9.1，我在 #15 有說明。同學理解後應該就能知道為什麼00123.123會出現error。


---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by kaiiiz** [comment]
ok，感謝助教的解釋，我原本以為八進制與浮點數混用的時候要做特判 XDD
