### ISSUE TITLE
make 後沒有出現 parser 

### ISSUE THREAD

**Issue by hsiao-po-sheng** [compiler-f20/discussion#18]
想請問在 hw1 的資料夾中用 make 後是不是應該要出現 parser ?
應為我只有在 src 檔案中有一個 scanner 的執行黨

還有我沒辦法直接用 make test 做測試會有問題嗎?
我現在都要先 make 然後再 make test 才能正確執行測試

另外是不是只要測試後出現 100/100 就表示這次的作業 Codes 的部分已經算是完成了?

![image](https://user-images.githubusercontent.com/44300502/94915084-dc49b180-04de-11eb-9f9d-da508f3eef15.png)

**Comment by chrisPyr** [comment]
@hsiao-po-sheng 

1. 應該是我們誤植了，指令是./scanner 而不是./parser

2. 要先make 產生scanner檔才能使用make test。

3. 是
  
---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
