### ISSUE TITLE
[macro]Is there a macro definition of  tokenInteger in the starter code?

### ISSUE THREAD

**Issue by CherryChiuyc** [compiler-f20/discussion#22]
@compiler-f20/2020f-teaching-team
I couldn't find the macro definition of tokenInteger in the starter code in scanner.l .
I don't know if there is a formal definition should I follow?
Would TAs provide the macro code? or I can just try another way to define integer

Thanks a lot.

**Comment by ran-ablaze** [comment]
@CherryChiuyc 

這次作業並不需要用到 tokenInteger 這個 macro ，所以助教在`scanner.l`中把他刪除了，但是沒有修改到`readme.md`中的部分，抱歉造成同學的困擾。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji :+1:，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
