### ISSUE TITLE
advance_case12 問題

### ISSUE THREAD

**Issue by JianShuiHuang** [compiler-f20/discussion#23]
不好意思請問一下
解答上最後一行是出現 
<id: ident>
Error at line 9: bad character "_"

但我看測資是 ident_

不是應該輸出
<id: ident_>
9: ident_
嗎

不好意思謝謝

**Comment by 5fe6eb50c7aa19f9** [comment]
@JianShuiHuang
"An identifier is a string of letters and digits beginning with a letter."

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by JianShuiHuang** [comment]
對阿那沒錯啊，投影片上letter的定義是[a-zA-Z_]，那ident_會在identifier裡吧?，'_'是letter阿，還是我誤會了甚麼嗎?

抱歉

**Comment by 5fe6eb50c7aa19f9** [comment]
作業的定義不包含'_'
