### ISSUE TITLE
Can i upload my homework through the terminal?

### ISSUE THREAD

**Issue by LiawiFelix** [compiler-f20/discussion#24]
I don't know why I can't install git in my docker, I realized that in hw0 it is root@compiler, but in this homework, it becomes student@compiler. Is there any difference if I directly upload the code through the linux terminal? 

Thank you 
![image](https://user-images.githubusercontent.com/55146311/95677336-a4470c00-0b79-11eb-97d3-6719078f0f99.png)

**Comment by 5fe6eb50c7aa19f9** [comment]
@LiawiFelix 
要git上傳時請先離開docker，

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by LiawiFelix** [comment]
Thank you TA
