### ISSUE TITLE
is it ok to define new token other than the one listed by TA?

### ISSUE THREAD

**Issue by eric0716336** [compiler-f20/discussion#25]
i read the issues before that for the token integer is deleted by the TA but forget to remove it in the README.md , however is it ok to use other than the one listed in the file?

**Comment by 5fe6eb50c7aa19f9** [comment]
@eric0716336 
你可以定義自己的macro。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
