### ISSUE TITLE
Is every row independent?

### ISSUE THREAD

**Issue by LiawiFelix** [compiler-f20/discussion#26]
I would like to ask whether every row is independent or not, for example " in line 1 and " in line 2, are they connected? or the result is error in line 1 and then exit.

Thank you

**Comment by 5fe6eb50c7aa19f9** [comment]
@LiawiFelix 
不太懂你的意思，你偵測到error就輸出他在第幾行然後結束即可。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by LiawiFelix** [comment]
For example 
![image](https://user-images.githubusercontent.com/55146311/95694186-20694e80-0c63-11eb-86a3-2c3a0623d6fe.png)
is the supposed answer should be error at line 1 or it should be connected with the lower quotes become a very long string? 

Thank you

**Comment by 5fe6eb50c7aa19f9** [comment]
@LiawiFelix 
第一行就錯。

**Comment by LiawiFelix** [comment]
Thank you TA
