### ISSUE TITLE
測資檔案結尾換行問題

### ISSUE THREAD

**Issue by wdzn** [compiler-f20/discussion#27]
Hi:

I noticed that in some testcase files an ending empty line does not appear. For example basic testcase `10_comment.p`:

```
/* 
comment 
*/
// comment
```

In this testcase, a reason answer should be:

```
1: /* 
2: comment 
3: */
4: // comment
```

However, since there is no empty line at the file end, the `\n` is not read, and the 4th line is not printed. The output turns out to be the following, which is same as the sample solution given by TAs.

```
1: /* 
2: comment 
3: */
```

Is this designed deliberately or a bug?

**Comment by 5fe6eb50c7aa19f9** [comment]
這不是bug。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
