### ISSUE TITLE
一直產生python UnicodeDecodeError

### ISSUE THREAD

**Issue by yen0515** [compiler-f20/discussion#28]
我在執行advanced string的1跟3的時候常常會跑出以下這樣的error
有時候重新儲存後make maketest就不會有問題了
有時候卻會一直顯示error
請問是我寫的東西需要更改嗎 謝謝
![1602489253181](https://user-images.githubusercontent.com/66356787/95720009-3f87d080-0ca3-11eb-8d4c-01e2509bdc53.jpg)

**Comment by Eric860730** [comment]
Hi, @yen0515 

你應該把某個不乾淨的字串（內容實際上是某個 address 殘渣）傳給你的 error message queue 裡，而那些 non-printable 字元有些 utf-8 不認得，就發生錯誤了。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji :+1:，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by CherryChiuyc** [comment]
Hi, @yen0515 
我也有遇到相同的問題。
我最後發現是我存string的char array開的不夠大，所以可能記憶體出錯。
最後把array大小開MAX_LINE_LENG就解決了。
你可以試試看

**Comment by yen0515** [comment]
好的謝謝助教謝謝同學 已經解決了
