### ISSUE TITLE
關於"Consecutive operators are not legal in an expression."的問題

### ISSUE THREAD

**Issue by SickZuluKush** [compiler-f20/discussion#34]
那"5--7"可以嗎? (5--7 = 12)

如果可以，那說明是否表示不能有連續的unary operators也不能有連續的binary operators，
但是unary operator可以接在binary operator的後面?

**Comment by 5fe6eb50c7aa19f9** [comment]
@SickZuluKush 
不可以

**Comment by SickZuluKush** [comment]
那在 advances_cases 中 general5 的"return sptr = -1;" 沒有問題，
代表只有relational operators後可接unary operators( "-" 和 "not")嗎?

**Comment by 5fe6eb50c7aa19f9** [comment]
@SickZuluKush 
同學抱歉，經過討論後我們決定把Consecutive operators改成合法，
也就是"--a"等同"-(-a)"，"5--7"等同"5-(-7)"，
如果同學這次作業在發現"--"或"not not"時輸出不合法，我們不會扣分。

**Comment by SickZuluKush** [comment]
知道了，謝謝
