### ISSUE TITLE
yyin讀檔失敗

### ISSUE THREAD

**Issue by 5ilianli** [compiler-f20/discussion#35]
不好意思，想請問一下，
我目前嘗試用：make test來測試我的parser
（前情提要一下：
我確定是在hw2-xxxxx資料夾下執行，
然後我沒有改動make其他檔，
只有修改scanner.l和parser.y，
scanner.l我改成用助教提供的，所以應該不是scanner的問題，
parser.y我有幾筆測資有對，所以某種程度上跑得動）
然而我的結果卻顯示如下，這個是decl.txt：
![result del](https://user-images.githubusercontent.com/58241047/98351007-1581be00-2057-11eb-8b54-16423419aabe.png)
我debug好幾天了，覺得應該是讀檔錯誤，
後來看了makefile等等，也不斷修改我的scanner和parser，
但結果還是一樣：讀檔錯誤，
剛剛我又看了test.py，發現有個地方怪怪的：
![Screen Shot 2020-11-06 at 5 30 38 PM](https://user-images.githubusercontent.com/58241047/98351203-5a0d5980-2057-11eb-9b16-e693b87e2204.png)
怪的地方在：資料夾名為「test_cases」但 python 對 basic 讀檔名稱卻是「"test-cases"」，
不知道是不是這裡出問題，或許test.py有錯之類的？又或是debug太久，我腦子進水了T^T
想請求助教協助QQ

**Comment by chrisPyr** [comment]
#32 
Duplicate. Already patched to all students.
