### ISSUE TITLE
Hw2 有兩個Pull requests

### ISSUE THREAD

**Issue by chrisPyr** [compiler-f20/discussion#36]
@compiler-f20/2020f-students 
各位同學好：
Hw2一共有兩個Pull request，請同學們都要merge，然後看一下說明，謝謝。

**Comment by nagi1999a** [comment]
助教您好：我這邊只有看到一個是[PATCH] 3-update-consecutive的，請問是正常的嗎？

**Comment by chrisPyr** [comment]
@nagi1999a 
正常，如果你是在我們發完patch才接受作業的話，產生的就是最新版，因此你應該是在我們發完第一次patch後才接受作業，所以只看到第二次的patch
