### ISSUE TITLE
About function invocation

### ISSUE THREAD

**Issue by LiawiFelix** [compiler-f20/discussion#37]
Dear TAs, 

I would like to ask about the "echo()" in the statement.p (screenshot attached on below), is it counted as function invocation? If yes, it must be a part of variable, function or compound. But follow the instruction in the README.md, I can't find a parse tree that derive until the function invocation. 

Thank you

![Screenshot from 2020-11-07 14-40-35](https://user-images.githubusercontent.com/55146311/98434059-45889a00-2107-11eb-9541-4b1a57985db3.png)

**Comment by 5fe6eb50c7aa19f9** [comment]
Functions may return one value or no value at all. Consequently, the return value declaration is **either a type name or is empty**. If no return value is declared, there is no colon before the terminating semicolon.

他是"function definition"。

**Comment by LiawiFelix** [comment]
ok TA, so it means that there are 3 types right? 

Thank you

**Comment by 5fe6eb50c7aa19f9** [comment]
2種Function，只是回傳數量不同。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by LiawiFelix** [comment]
謝謝 助教
