### ISSUE TITLE
[Pull Request] 看不到有任何pull requests

### ISSUE THREAD

**Issue by CherryChiuyc** [compiler-f20/discussion#38]
助教您好,
進入 hw2 的repository 後並沒有看到有任何的pull request 
請問要怎麼merge? 
但是在branch裡面有看到三個branch, 是要點及旁邊的 new pull request 按鈕嗎QQ
（對於github實在不熟悉
謝謝助教

@compiler-f20/2020f-teaching-team

**Comment by ran-ablaze** [comment]
若是在助教打patch之後才點擊連接接受作業的同學並不需要pull request，接收到的作業就會是最新版本的。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji :+1:，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
