### ISSUE TITLE
shift/reduce conflicts

### ISSUE THREAD

**Issue by LiawiFelix** [compiler-f20/discussion#39]
Dear TAs,

Is it ok to have shift/reduce conflicts after make file? 

Thank you

**Comment by chrisPyr** [comment]
@LiawiFelix 
As long as you can make sure after doing the make file, the result is correct, then we will ignore all the warnings. But it’s highly recommended for you to deal with the problem.

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji :+1:，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by LiawiFelix** [comment]
Thank you TA
