### ISSUE TITLE
關於 HW0 中 Docker 安裝教學文消失的事情

### ISSUE THREAD

**Issue by hsiao-po-sheng** [compiler-f20/discussion#4]
問題如題目

在點擊"這篇教學"後跳出如下頁面，請問是正常的嗎？

![image](https://user-images.githubusercontent.com/44300502/93454507-b08ad100-f90d-11ea-8d69-5c28339073d9.png)

**Comment by 5fe6eb50c7aa19f9** [comment]
網址應該是出問題了，
Ubuntu下安裝Docker請先參考下面這個，
https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

**Comment by chrisPyr** [comment]
已經發patch給同學，請同學看一下pull request

**Comment by ran-ablaze** [comment]
@compiler-f20/2020f-students 
請同學檢查一下自己的hw0 repo底下應該有Pull request，看一下裡面的說明，之後作業有修改都會用這種形式發給同學。
