### ISSUE TITLE
integer_constant 的定義

### ISSUE THREAD

**Issue by kaiiiz** [compiler-f20/discussion#40]
助教您好：

integer_constant 在 variable 下面的定義是：

```
var identifier_list: array integer_constant of type;
```

where integer_constant should be a non-negative integer constant which represents the size of the array.

在 for 後也使用到 integer_constant 這個表示：

```
for identifier := integer_constant to integer_constant do
<one compound statement>
end do
```

所以在 for 上的 assignment 也是 non-negative integer constant 嗎？還是可以有負數？

**Comment by ran-ablaze** [comment]
此次作業只需要處理語法相關問題即可。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji :+1:，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by kaiiiz** [comment]
好的，所以

> where integer_constant should be a non-negative integer constant which represents the size of the array.

這句話是在說明語義上的錯誤，integer_constant 在語法上是允許有負號的，這樣的理解是正確的嗎？

**Comment by 5fe6eb50c7aa19f9** [comment]
對

**Comment by kaiiiz** [comment]
我寫到後面跑測試的時候發現 advance_cases/arrayErr.p 裡面有：

```
var c : array -1 of integer;          //declaration error
```

在答案裡面是：

```

|--------------------------------------------------------------------------
| Error found in Line #14:         var c : array -
|
| Unmatched token: -
|--------------------------------------------------------------------------
```

所以這個 declaration error 應該是指語法錯誤而不是語義錯誤？

那

> where integer_constant should be a non-negative integer constant which represents the size of the array.

這句話的解釋是不是又跟我的理解不太一樣，應該是在說明語法的錯誤，而不是語義上的錯誤？

**Comment by ran-ablaze** [comment]
同學抱歉，之前講錯了><
在 for 跟 array 宣告上的 integer_constant 都只能是純整數不包含任何符號，允許有符號的在目前的 spec 裡指的應該是 integer。
---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji :+1:，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by kaiiiz** [comment]
ok，我了解了，感謝助教的解釋
