### ISSUE TITLE
function invocation spec 描述問題

### ISSUE THREAD

**Issue by kaiiiz** [compiler-f20/discussion#41]
助教您好：

function invocation 在 spec 是這樣寫的：

> The function invocation has the form:
>
> ```
> identifier (\<expression separated by zero or more comma>)
> ```

請問 expression separated by zero or more comma 在我看起來好像是：一個 expression 被零個或很多個 comma 隔開？

但感覺這邊應該要是很多 expression，每個 expression 間用逗號隔開？還是真的是上面的意思？因為兩邊都沒加 s 我看不出來哪邊是複數 XD

**Comment by kaiiiz** [comment]
我重新回去看一下，看到 expression**s** 了，所以是我眼睛&英文問題，抱歉打擾助教XD

**Comment by kaiiiz** [comment]
話說 expressions separated by zero or more comma 在英文上是不是表示 expressions 間也可以不要有 comma？感覺有點 ambiguous

**Comment by 5fe6eb50c7aa19f9** [comment]
@kaiiiz 
把他理解成expressions之間有一個comma即可。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by ypyou** [comment]
```
expressions separated by zero or more comma
```
should be revised as
```
zero or more expressions, separated by commas
```

**Comment by chrisPyr** [comment]
@compiler-f20/2020f-students  
Please take a look at this issue and teacher's comment, there are some words in spec should be revised. 
TAs won't patch for this revision, so please note that.
