### ISSUE TITLE
make result 

### ISSUE THREAD

**Issue by eric0716336** [compiler-f20/discussion#42]
is it normal to have this after running make?
![scanner warn](https://user-images.githubusercontent.com/55134405/98823488-1d819980-246d-11eb-9e4e-b92b9be6663b.png)

**Comment by 5fe6eb50c7aa19f9** [comment]
@eric0716336 
正常。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
