### ISSUE TITLE
expression 定義問題

### ISSUE THREAD

**Issue by JianShuiHuang** [compiler-f20/discussion#44]
不好意思可以請問一下關於expression的定義嗎?

因為我覺得上面沒寫的很清楚，只有說Valid components of an expression include literal constants, variable reference, function invocations 以及上面一些operator

不知道可不可以請問一下expression完整結構大概是如何

還是是我自己理解不好，自己應該看懂?

不好意思，謝謝

**Comment by chrisPyr** [comment]
意思就是一個expression是由以上幾種不同components組合而成。
例如：2 + a 是一個expression ，他的components有：2 是literal constant , a 是variable ,+是operator，然後要用infix表示。
           foo() 也是一個expression，他的component只有一個function invocation。
---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
