### ISSUE TITLE
請問 KeyWord def 要做嗎 ?

### ISSUE THREAD

**Issue by hsiao-po-sheng** [compiler-f20/discussion#45]
因為我並沒有看到功課中有要求針對 def 做實作
所以想知道要不要實作 def 
如果要的話又要怎麼做 ?

**Comment by chrisPyr** [comment]
@hsiao-po-sheng 

Spec跟測資中沒有的就不需要做。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
