### ISSUE TITLE
如何確定 PULL Request 有被整合 ?

### ISSUE THREAD

**Issue by hsiao-po-sheng** [compiler-f20/discussion#46]
![image](https://user-images.githubusercontent.com/44300502/99185810-364cc080-2787-11eb-9040-0c499ef840f0.png)

只要像圖片中一樣就是已經整合了嗎 ?

**Comment by Eric860730** [comment]
對
---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
