### ISSUE TITLE
忘記寫報告

### ISSUE THREAD

**Issue by hsiao-po-sheng** [compiler-f20/discussion#48]
因為繳完作業後忘記寫報告
請問根據之前 hw1 的評分標準
還是 penalty * ( 95% test case + 0 ( 報告 ））嗎？

**Comment by ran-ablaze** [comment]
沒綽，所以建議同學就不要補交了，不然分數會算成遲教的分數。

**Comment by hsiao-po-sheng** [comment]
那麼請問hw2大概什麼時候會知道成績呢？

**Comment by ran-ablaze** [comment]
因為考量到遲交的同學，我們會在遲交也截止之後才統一批改，所以最快下個禮拜才會出來。
