### ISSUE TITLE
hw0 問題

### ISSUE THREAD

**Issue by ruowenyu** [compiler-f20/discussion#5]
![image](https://user-images.githubusercontent.com/55253053/93570892-441fd880-f9c6-11ea-91e7-b8180bd7cc08.png)

無法進入docker
請問是發生了什麼問題

**Comment by 5fe6eb50c7aa19f9** [comment]
這應該是python版本的問題，
你可以下 "python3 --version" 指令查看你的版本，
3.6版以上應該都可行。

**Comment by ran-ablaze** [comment]
@ruowenyu 
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji :+1:，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
