### ISSUE TITLE
Todo hint

### ISSUE THREAD

**Issue by LiawiFelix** [compiler-f20/discussion#50]
Dear TAs,

I am quite confuse in doing this homework, do we only need to modify the part that has comment "TODO" to accomplish this homework? Thank you

**Comment by 5fe6eb50c7aa19f9** [comment]
@LiawiFelix 
如果同學打算以我們給的 template code 為基底來做作業的話，基本上是這樣沒錯。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by LiawiFelix** [comment]
ok, Thankyou TA
