### ISSUE TITLE
visitChildNodes function 

### ISSUE THREAD

**Issue by eric0716336** [compiler-f20/discussion#51]
for the visitChildNodes() , how do we access child nodes(ex: from program to compound) from the current node? do we have to add attribute child nodes by ourselves to the AstNode ?

**Comment by ran-ablaze** [comment]
Yes, you have to add attribute child nodes by yourselves to the AstNode and access them.

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
