### ISSUE TITLE
test.py command 問題

### ISSUE THREAD

**Issue by kaiiiz** [compiler-f20/discussion#52]
助教你們好：

test.py 第 49 行

```py
clist = [self.parser, test_case]
```

是否應該改為

```py
clist = [self.parser, test_case, '--dump-ast']
```

不然依照 spec 說的要加 dump-ast 才輸出 AST 資訊的話，測試腳本不會輸出任何東西

**Comment by kaiiiz** [comment]
另外，test/.gitignore 中是否應該將

```
outputs/
```

改為

```
result/
```

因為預設腳本是輸出到 result 這個資料夾下

**Comment by chrisPyr** [comment]
@kaiiiz  

同學你好，助教們正在debug，感謝同學回報，等到測試完成會發patch。
