### ISSUE TITLE
sematic action

### ISSUE THREAD

**Issue by LiawiFelix** [compiler-f20/discussion#53]
Dear TA, 
Is there a must that we need to put the action after the "END" on the programnode? Because if we put on the END, shouldn't it first handle the compound action first, then the program? (Maybe I misunderstand). But if it handle the compound first, the compound become the root, not the program because I can't declare child of root before the root itself. Thank you

![image](https://user-images.githubusercontent.com/55146311/100569243-65773c00-3308-11eb-9bbf-351cca51c126.png)
![image](https://user-images.githubusercontent.com/55146311/100569170-38c32480-3308-11eb-95f5-c202419103c6.png)

**Comment by 5fe6eb50c7aa19f9** [comment]
@LiawiFelix 
先處理compound statement應該沒錯，這樣最後ProgramNode就能將CompoundStatementNode接起來，麻煩參照TODO:

    ProgramNode(const uint32_t line, const uint32_t col,
                const char *p_name
                /* TODO: return type, declarations, functions, compound statement */);

**Comment by Eric860730** [comment]
@LiawiFelix 
可能你有點誤解了 Action 被呼叫的時機，可以再去看看老師的講義關於 YACC Actions 的部分。
---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
