### ISSUE TITLE
ProgramNode 的 return type 一定是 void 嗎

### ISSUE THREAD

**Issue by kaiiiz** [compiler-f20/discussion#56]
助教你們好：

請問 ProgramNode 的 retrun type 一定是 void 嗎？看 Output format：

```
program <line: {line_number}, col: {col_number}> {program_name} void
  {zero or more outputs of declaration node}
  {zero or more outputs of function node}
  {output of compound statement node}
```

Return type 感覺是寫死的 void？看 spec 好像沒有明確定義到這件事，測資也沒有非 void 的情況，想確認一下，感謝

**Comment by ran-ablaze** [comment]
ProgramNode 的 retrun type 一定是 void 。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by kaiiiz** [comment]
好的，感謝助教。

但如果一定是 void，這樣好像就找不到存這個資訊的用途了？

**Comment by ran-ablaze** [comment]
那是因為我們作業所規定的語言是較簡單的，如果想讓你的compiler能夠處理更複雜的語言，這個資訊就是必要的。
