### ISSUE TITLE
關於傳送 P language 中 type 的方式

### ISSUE THREAD

**Issue by denny3388** [compiler-f20/discussion#58]
我有看到 spec 裡面有提到：You may need to find a way to convey the type of P language. DO NOT use string for it. 
但我看不太懂下面的 suggestion 部份： Use an enum and a list of integer for the scalar part and the structured part of type respectively.
我不太清楚所謂的 "scalar part" 和 "the structured part of type" 指的是什麼QQ 希望有好心人能幫忙解答或是舉個例子，感謝！

**Comment by ran-ablaze** [comment]
scalar part 指的是variable或是constant的data type。
    ex: int or float
the structured part of type指的是其他組成variable的部分。
    ex: array的dimension

**Comment by denny3388** [comment]
@ran-ablaze 請問是指將 type 儲存在 node 裡面的時候盡量不要用 string 嗎？還是說只有從 scanner 傳到 parser 裡面的時候不要用呢？謝謝助教！

**Comment by ran-ablaze** [comment]
是指將 type 儲存在 node 裡面的時候不要用 string。

**Comment by denny3388** [comment]
@ran-ablaze 了解了！感謝助教～～
