### ISSUE TITLE
test.py的問題

### ISSUE THREAD

**Issue by hedy881028** [compiler-f20/discussion#59]
[助教好，想請問在什麼情況下可能會出現如圖的問題QQ
(我看到之前有一個人有問過，但他自己解決了，所以我還是想上來問問助教)
![1606974729329](https://user-images.githubusercontent.com/55384702/100995421-b5693380-3592-11eb-8b17-99c106b65d15.jpg)

**Comment by cksc33milktea** [comment]
同學你好,我當初是把第一個rule(head為program的那個rule)action裡面的free($1)註解,就沒問題了
給你當作參考.

**Comment by chrisPyr** [comment]
@cksc33milktea

同學可以請你分享一下怎麼解決的嗎?
另外也可以參考看看: #28

**Comment by cksc33milktea** [comment]
我的case是把第一個rule(head為program)action裡面的free($1)這行刪掉 然後就可以了
給大家當作參考
