### ISSUE TITLE
想請問使用 Makefile-vp 時得到的錯誤訊息

### ISSUE THREAD

**Issue by 5ilianli** [compiler-f20/discussion#60]
以下是我在使用 Makefile-vp 時得到的錯誤訊息：

![Makefile-vp 時得到的錯誤訊息](https://user-images.githubusercontent.com/58241047/101025894-291a3900-35b1-11eb-8cf6-b840f4bf465c.png)

但我嘗試 debug 後，還是出現了相同的情況 QQ

我確定我在 AstDumper.hpp 有 #include "visitor/AstNodeVisitor.hpp"

真的不太知道為啥還是有這樣的錯誤訊息 T^T

會是 makefile 本身的問題嗎？

**Comment by 5ilianli** [comment]
對不起！我後來自己解決掉了，不好意思驚擾了！

**Comment by ran-ablaze** [comment]
@5ilianli 請同學分享一下自己怎麼解決的，這樣之後大家有類似的問題時可以做參考。

**Comment by 5ilianli** [comment]
我遇到的情況是：
1. 在 hw3-xxx 下，輸入：make test，有成功編譯
2. 在 hw3-xxx/src 下，輸入：make clean && make，並回到 hw3-xxx 下，輸入：make test 後，有成功編譯
3. 但是在 hw3-xxx/src 下，用 Makefile-vp 編譯 .... 就悲劇了，並出現截圖上面的錯誤訊息
解決辦法：
後來在 AstDumper.hpp 中，把 #include "ast.hpp" 註解掉，就成功編譯了
（大概是我之前日夜寫作業的時候，因為先寫了一個不用 vp 的版本，
但在後來改用 vp 後，沒察覺到有 double include 的情況，
所以可能導致 compiler 無法認知到底應該使用哪個 class 並實作 virtual function 吧）
所幸這是可以挽救的悲劇 QQ
