### ISSUE TITLE
vector在union的問題

### ISSUE THREAD

**Issue by ruowenyu** [compiler-f20/discussion#61]
![image](https://user-images.githubusercontent.com/55253053/101063692-0d715b80-35ce-11eb-82c4-d300668680e2.png)

已經有#include <vector> ， 且已使用pointer，但還是有error，請問是什麼問題呢？
謝謝！

**Comment by ran-ablaze** [comment]
請參考作業說明中的`%code Directive`

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
