### ISSUE TITLE
用 Visitor Pattern 印 AST 的話是否還需要實作每個 Node 的 print() 函式

### ISSUE THREAD

**Issue by yuko29** [compiler-f20/discussion#62]
每個 Node 都有一個 `print()` 函式，但我用 `Visitor Pattern` 印出 AST 過程並不會需要用到 `print()`，請問有需要把每個節點的`print()` 函式補完嗎？

**Comment by chrisPyr** [comment]
@yuko29 

如果同學用不到就不需補完實作。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
