### ISSUE TITLE
make docker-pull failed

### ISSUE THREAD

**Issue by penny644** [compiler-f20/discussion#63]
剛剛把整個資料夾hw3從本機複製到ubuntu裡之後make docker就會出現以下訊息
docker pull ianre657/compiler-s20-hw3:latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io: no such host
Makefile:24: recipe for target 'docker-pull' failed
make: *** [docker-pull] Error 1

想請問助教要如何解決，謝謝助教

**Comment by 5fe6eb50c7aa19f9** [comment]
@penny644 
你的系統可能有些問題，
[參考連結](https://stackoverflow.com/questions/47580528/error-response-from-daemon-get-https-registry-1-docker-io-v2-dial-tcp-look)

**Comment by penny644** [comment]
> @penny644 
> 你的系統可能有些問題，
> [參考連結](https://stackoverflow.com/questions/47580528/error-response-from-daemon-get-https-registry-1-docker-io-v2-dial-tcp-look)

剛剛再打開來試，不知道為什麼它自己好了，謝謝助教

**Comment by penny644** [comment]
不好意思，想再問助教我剛剛要commit的時候，出現以下訊息，想請問助教我可以把已經下載到虛擬機的那個資料夾刪除，重新clone一次，再一一重寫檔案再commit嗎，不知道會不會有什麼影響?
![1607133616765](https://user-images.githubusercontent.com/70514284/101230591-2e76a100-36e1-11eb-93b7-ee3a13c0c8b0.jpg)
