### ISSUE TITLE
請問評分時可以直接用 Makefile-vp 嗎 ？

### ISSUE THREAD

**Issue by yuko29** [compiler-f20/discussion#65]
我在 spec 的地方有看到
> TA would use `src/Makefile` to build your project by simply typing `make clean && make` on CS workstation.
 You have to make sure that it will generate an executable named 'parser'. No further grading will be made if the make process fails or the executable 'parser' is not found.

因為我直接用 `vp` 實作，有用到 `include/visitor/` 和 `lib/visitor` 內的檔案
並且在 `parser.y` 中我是直接建一個 `AstDumper` 去 dump AST：
```c
#include "AST/AstDumper.hpp"

...

int main(int argc, const char *argv[]) {
    ...
    if (argc >= 3 && strcmp(argv[2], "--dump-ast") == 0) {
            //root->print();
            AstDumper Visitor;
            root->accept(Visitor);
    }
    ...
}
```
但是 `src/` 內的 `Makefile` 沒有編譯到 `lib/visitor` 內的檔案，在 `Makefile-vp` 內才有
所以我用 `src/Makefile-vp` 可以編譯成功，用`src/Makefile` 編譯會失敗
錯誤訊息如下，原因應是找不到 `AstNodeVisitor` 的 destructor 的 definition，該 definition 是在 `lib/visitor/AstNodeVisitor.cpp`裡的
```
parser.o: In function `AstDumper::~AstDumper()':
/home/student/src/include/AST/AstDumper.hpp:11: undefined reference to `AstNodeVisitor::~AstNodeVisitor()'
```
由於`make clean && make` 會用到的是`src/Makefile` 
想請問助教到時候評分是在`src/` 下 `make clean && make` 沒過不行了嗎，還是可以用直接用 `Makefile-vp` 評分呢？

**Comment by JohnnyWu0425** [comment]
也有一模一樣的問題！

發現助教在 Project Structure 中有提到
如果是使用 visitor pattern 的話就使用 Makefile-vp

因此，我將原來的 Makefile 改名為 Makefile-base；並把 Makefile-vp 改名為 Makefile。
想請問這樣子是可以的嗎？
謝謝！
![image](https://user-images.githubusercontent.com/44256275/101272910-95708480-37cb-11eb-8b64-8d14757c92de.png)

**Comment by chrisPyr** [comment]
@yuko29 
@JohnnyWu0425 

可以參考這邊的討論哦：
[makefile problem](https://github.com/compiler-s20/discussion/issues/69)

**Comment by JohnnyWu0425** [comment]
了解！謝謝！
