### ISSUE TITLE
沒有使用 AST 通過 test case 的意思

### ISSUE THREAD

**Issue by hsiao-po-sheng** [compiler-f20/discussion#66]
要怎麼知道有沒有都使用 AST 的方法?
我在寫報告的時候才看到，不知道有沒有可能分數會被減半

**Comment by 5fe6eb50c7aa19f9** [comment]
@hsiao-po-sheng 
助教會大概看一下你們的實作方式。

**Comment by hsiao-po-sheng** [comment]
所以不要 hard code 都可以嗎？

**Comment by hsiao-po-sheng** [comment]
我是利用 src 裡面附上的各種 node 來實作的

**Comment by 5fe6eb50c7aa19f9** [comment]
只要有把樹建起來大概就沒問題了。

**Comment by hsiao-po-sheng** [comment]
所以說只要每一層的 node 之間有遞迴關係就可以了嗎

**Comment by 5fe6eb50c7aa19f9** [comment]
不太懂你所謂的"每一層的 node 之間有遞迴關係"是什麼，
基本上只要能透過root來traverse整顆樹的話就沒問題了。

**Comment by hsiao-po-sheng** [comment]
所以像是我的 program node 裡面有各種 child node 就算是了吧？

**Comment by 5fe6eb50c7aa19f9** [comment]
是的。
