### ISSUE TITLE
visitor pattern : AstDumper的問題

### ISSUE THREAD

**Issue by HueiEeicSy** [compiler-f20/discussion#67]
![擷取](https://user-images.githubusercontent.com/64456889/101340000-1e65e980-38ba-11eb-95f5-92dcc99e51b5.JPG)
我的VP是用AstDumper去實作，過程中只有動到AstDumper.cpp，而AstDumper.h、AstNodeVisitor.h、AstNodeVisitor.cpp都沒動到，AstDumper也都把功能寫好了。但在Parser 宣告AstDumper時就會發生以上錯誤，該如何解決。

**Comment by HueiEeicSy** [comment]
AstDumper.cpp只有將fixed拿掉以及完成visit的功能

**Comment by ran-ablaze** [comment]
你的AstDumper可能有其他的virtual function還未被定義。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by HueiEeicSy** [comment]
已經確認過所有virtual function(原本AstNodeVisitor.h裡的，我本身沒多加)都有被定義了，還是同樣的狀況

**Comment by ran-ablaze** [comment]
那你可能需要把你的code push到github上，或是詢問同學是否遇到類似的問題，不然助教也是無法通靈看到你的code的

**Comment by HueiEeicSy** [comment]
已經push上去了 麻煩助教過目

**Comment by HueiEeicSy** [comment]
parser裡的AstDumper vist; 如果取消註解就會有上述的情況

**Comment by chrisPyr** [comment]
@HueiEeicSy 

如果你要使用VP的話，請把/src/lib/AST/Astdumper.cpp中的第23 #ifdef 還有結尾的 #endif 註解掉。

**Comment by HueiEeicSy** [comment]
註解掉後vtable沒問題了 ，但還是有意點問題
![擷取](https://user-images.githubusercontent.com/64456889/101351851-3181b500-38cc-11eb-9d7c-45ed01b242a8.JPG)

**Comment by HueiEeicSy** [comment]
AstNodeVisitor.cpp已經有定義destructor，不應該報錯才對

**Comment by chrisPyr** [comment]
@HueiEeicSy 

你要用makefile-vp編譯。
請參考 #65

**Comment by HueiEeicSy** [comment]
@chrisPyr  剛剛測試的時候忘記切回來了，目前沒有編譯錯誤了，看來是沒註解掉那兩行的問題，感謝教授和助教的解惑。

**Comment by chrisPyr** [comment]
我們兩個都是助教喔 XD
