### ISSUE TITLE
invalid use of incomplete type

### ISSUE THREAD

**Issue by minyunh** [compiler-f20/discussion#69]
我將compound, assign, print......這些內歸類為將statement作為parent 的node
在.hpp欓內繼承的時候
會顯示出error invalid use of incomplete type
![螢幕快照 2020-12-08 下午02 49 56 上午](https://user-images.githubusercontent.com/66958434/101392446-bf779300-3900-11eb-9850-2168da94e32c.png)
上網查到的解決方式是在對應的.cpp欓內include statement的.hpp欓
但是一樣有error
想請問助教要如何解決，謝謝助教

**Comment by 5fe6eb50c7aa19f9** [comment]
你的"statement.hpp"要改下面的define，因為__AST_EXPRESSION_NODE_H已經被define過了:
#ifndef __AST_EXPRESSION_NODE_H
#define __AST_EXPRESSION_NODE_H

**Comment by minyunh** [comment]
有更改statement.hpp下的define了
但是噴一樣的error

**Comment by 5fe6eb50c7aa19f9** [comment]
我用我的電腦改完以後那個地方沒出現error，
你可能要在確認一下。

**Comment by minyunh** [comment]
但現在出現另一個error
redefinition of class StatementNode
但是在statement.hpp中
只有include AST/ast.hpp
沒有include error下面提到的這些欓
是有哪裡又重複define了嗎
謝謝助教ＱＱＱ

**Comment by minyunh** [comment]
上面的問題解決了
因為是included的問題
好像是順序的關係
所以我將發生衝突的地方
放到同一個.hpp欓了
就沒有error了
謝謝助教
