### ISSUE TITLE
Can someone share how to use HackMD in docker?

### ISSUE THREAD

**Issue by LiawiFelix** [compiler-f20/discussion#7]
Currently I don't know how to install HackMD in docker in order to change "student name " in the student_info.init file, so I plan to use vim, but the problem is it doesn't support mandarin characters, so i end up having error UTF-8 when make the file.

Can someone give me some tips how to edit the student name (using HackMD or another tools)?
You can reply in chinese, Thank you very much 
![image](https://user-images.githubusercontent.com/55146311/93594861-3760ac00-f9e9-11ea-844c-51ff0fe2c796.png)

**Comment by Eric860730** [comment]
在Step3. 獲取 hw0 Docker image的最下面有說明
我們推薦的使用方式是：

開啟一個專門跑 Docker 的終端機，編譯動作都在 Docker 環境下。
在原本系統開啟慣用編輯器來寫作業。所有在編輯器撰寫的改動都會即時映射到 Docker 環境中。

試試看先修改完student_info.init後再進入Docker內編譯。

**Comment by LiawiFelix** [comment]
了解, 謝謝
