### ISSUE TITLE
請問作業遲交還可以繳交嗎?

### ISSUE THREAD

**Issue by CherryChiuyc** [compiler-f20/discussion#71]
@chrisPyr
助教您好，
由於記錯作業3繳交時間，這幾天還在趕作業三這份作業。
但是剛剛看到作業4已經發布，請問這樣我還可以繳交嗎?這樣算是sample code release嗎?
因為想要在這幾天還可以補交作業，請問助教可以給我補教機會嗎?
我還沒有accept 作業4，但是很慌張作業3才經過兩天就不能遲交了QQ
謝謝助教

**Comment by 5fe6eb50c7aa19f9** [comment]
@CherryChiuyc 
HW3到12/15 8:00前都還可以交，但遲交一天扣15%。

**Comment by chrisPyr** [comment]
@CherryChiuyc 

這次是助教疏失過早將sample code 釋出，所以這次允許同學補交，但是之後的作業不會通融。
所以一樣按照規定扣分，並且如果有抓到抄襲sample code的嫌疑會直接算0分。
