### ISSUE TITLE
Report error to stderr

### ISSUE THREAD

**Issue by LiawiFelix** [compiler-f20/discussion#72]
Dear TAs,
I would like to ask about the statement about our parser should report the error to the stderr, is that mean we need to use stderr method to print the error? Thank you

**Comment by 5fe6eb50c7aa19f9** [comment]
@LiawiFelix 
能輸出到`stderr`即可，fprintf的用法:
fprintf(stderr, ... )

**Comment by LiawiFelix** [comment]
謝謝助教
