### ISSUE TITLE
Spec 錯字問題

### ISSUE THREAD

**Issue by kaiiiz** [compiler-f20/discussion#73]
助教你們好：

請問作業四的 Spec 在 0x01. Semantic Analysis 的說明，是不是都把 Omit 打錯成 Emit 了？

雖然是不影響閱讀的小問題但想說還是回報一下

**Comment by chrisPyr** [comment]
@kaiiiz 

是的，應該是omit 沒錯。

@compiler-f20/2020f-students 

由於應該影響應該不大，所以這邊也先不發patch，等作業結束之後助教再來修正，感謝同學回報。
