### ISSUE TITLE
使用PType裡寫好的get_PTypeCString()，array卻有少

### ISSUE THREAD

**Issue by jeff0625** [compiler-f20/discussion#76]
在Dump的時候要print出type，所以使用了再PType寫好的get_PTypeCString()來實現，
可是再第一個測資的第二個symbol_table裡面的int [1922][1]卻只跑出了 int [1922]
想問這是什麼問題畢竟如果能用寫好的function的話就不用再自己寫一個了。

**Comment by 5fe6eb50c7aa19f9** [comment]
@jeff0625 
你可能忘記使用"PType::setDimensions(std::vector<uint64_t> &dims)"來設定維度了。

**Comment by jeff0625** [comment]
所以我應該要從node去得到這些資訊囉

**Comment by jeff0625** [comment]
助教但是我是在visitors pattern的時候直接把varible node中的ptype傳入 應該不會有錯吧QWQ?

**Comment by 5fe6eb50c7aa19f9** [comment]
剛看了你的程式碼，你用了:
PType *temp = p_variable.type.get();
我想你的使用方式可能有誤，使用:
p_variable.getTypeCString()
就可以得到陣列的字串了。

**Comment by jeff0625** [comment]
助教我後來改用wsl來跑就正確了，好像是虛擬機顯示的問題，謝謝助教!
