### ISSUE TITLE
undefined reference to `opt_dum'

### ISSUE THREAD

**Issue by CherryChiuyc** [compiler-f20/discussion#78]
在make的時候一直出現 undefined reference to `opt_dum'，不知道要怎麼解決。
確定在scanner.l 裡面有宣告static int32_t opt_dum = 1;
且在parser.y裡面也用了extern int32_t opt_dum;
但是在使用opt_dum來判斷是否要dump symbol table時，卻出現以下錯誤 

![opt_dum](https://user-images.githubusercontent.com/44312504/102681962-93adb480-4200-11eb-999a-2d55e58fdf9d.png)

**Comment by chrisPyr** [comment]
@CherryChiuyc 
同學請妳把code push上github

**Comment by CherryChiuyc** [comment]
code已push上github。謝謝助教

**Comment by chrisPyr** [comment]
@CherryChiuyc 

同學我現在人在外頭還無法幫妳看，但妳先試試把static 拿掉

**Comment by CherryChiuyc** [comment]
嘗試把static拿掉後，可以make了！
可是卻出現別的warning。

![拿掉static](https://user-images.githubusercontent.com/44312504/102684589-d11c3d00-4214-11eb-9869-5972bd67f34a.png)

之後離開docker環境，再回來make就沒有問題了。

![make成功](https://user-images.githubusercontent.com/44312504/102684611-0e80ca80-4215-11eb-8540-f77e09772e02.png)

謝謝助教！
