### ISSUE TITLE
Segmentation fault (core dump)

### ISSUE THREAD

**Issue by CherryChiuyc** [compiler-f20/discussion#79]
(移除issue)

**Comment by ran-ablaze** [comment]
請同學不要把程式碼實作公開
建議的做法是在你的repo裡開一個issue並tag助教群，感謝🙏

**Comment by CherryChiuyc** [comment]
了解了，謝謝助教

**Comment by Naetw** [comment]
Hi, @CherryChiuyc 

可以試著用 `gdb` 去縮小問題的範圍（[入門教學](http://www.study-area.org/goldencat/debug.htm)），以你的情況最快的方式是：

1. 確保你的 Makefile 的編譯器選項有加入 `-g`，代表編譯器會在你的執行檔裡頭加上除錯用的資訊
2. 使用 `gdb` 去執行你的程式（最初的版本，symbol entry 裡有放一堆參數的）
    ```
    gdb ./parser
    ```
3. 執行程式（註：以下的 `(gdb)` 是進入 `gdb` 之後的提示字串 (prompt)，不用照著輸入）：
    ```
    (gdb) > run <input file>
    ```
    把 `<input file>` 替換成某個 .p 測資
4. 接著你應該會看到 segmentation fault，這時候下指令 `backtrace` or `bt`
    ```
    (gdb) > backtrace
    ```
5. 你應該會看到一堆函式名稱，最上面的函式（編號 0）會是發生問題的函式，若你第一步有做好，可以看到在哪個原始碼檔案的第幾行出問題的
6. 接著根據發生問題的程式碼，你可以自己空想可能發生問題的狀況，例如某個變數應該要是個有效的指標，但你給它 `NULL`，那就可能發生 segmentation fault，若你不確定是讀取到什麼東西發生問題，你也可以用 `print` 指令去把內容印出來，舉例來說 `printf("%s\n", char_ptr);` 這裡面我會需要 `char_ptr` 是個有效的指標，指向某個有效的位址，但是發生了 segmentation fault，所以我想看看它到底存了什麼東西：
    ```
    (gdb) > print char_ptr
    ```
    若確定是某個變數的內容出現問題，你可以根據你自己寫的程式判斷這個變數是在哪裡被改寫的，進而確認是不是你哪邊忘記給它正確的資料或是哪邊不小心改動到它等等問題。若你的程式中有很多改動他的地方，但你不確定是哪邊發生的，你可以重新看 step 4 的 `backtrace` 印出來的資訊，編號 0 會是發生問題的函式，那編號 1 會是呼叫該函式的函式，以此類推，可以知道整個程式的執行路徑，依照這個路徑去檢查你的變數哪邊出問題。
    
其他 `gdb` 的用法可參考上面的入門連結或是餵給 Google 找找看資料

**Comment by CherryChiuyc** [comment]
助教您好， @Naetw 
我確認過src/makefile 裡面編譯器選項有加上-g 的指令。
所以我嘗試gdb，並且測試第一個測試檔案1_table.p
接著我做backtrace，看了編號0的函式，但是我並不知道這個函式名是來自哪裡。
看起來不是來自sematic analyzer
請問我忽略什麼了嗎？還是我搞錯gdb的用法？
謝謝助教
![raise](https://user-images.githubusercontent.com/44312504/102709737-f9c13700-42e7-11eb-8998-9b9c5239d4d4.png)

**Comment by Naetw** [comment]
前面幾個編號都是進到 GNU 的 C 函式庫 (libc) 的某幾個函式，遇到這種狀況（好幾個編號不是你寫的程式），你就往下找，找到第一個跟你有關的，在截圖中就是編號 4 `main`。看這個狀況你可以檢查 `parser.y` 裡的 main 函式，應該是某個 `assert()` 壞掉了。

事實上，在你下 `backtrace` 之前他就有告訴你錯誤發生的原因了（`assert` 就是這麼方便！），你可以從 `r test/test_cases/1_table.p` 往下看，看到你的某個 assertion fails，你的路徑應該給錯了，`test_cases` 前應該還有一個 `basic_cases`？
