### ISSUE TITLE
無法修改student_info.ini

### ISSUE THREAD

**Issue by hedy881028** [compiler-f20/discussion#8]
![1600430636791](https://user-images.githubusercontent.com/55384702/93617037-0e9bdf00-fa08-11ea-80e4-25f16aa7ae36.jpg)
助教好，我要修改student_info.ini時，用vim指令打開後就會出現這個畫面，沒辦法顯示出ini檔的內容
已經檢查過我的python3版本了，是3.6.8
麻煩助教了，謝謝

**Comment by 5fe6eb50c7aa19f9** [comment]
可以把你到這畫面前下的指令完整打出來?

@hedy881028

**Comment by hedy881028** [comment]
我只有安裝vim到我的虛擬機而已，就是sudo apt install vim
我會再載一份試試看，謝謝助教

**Comment by ran-ablaze** [comment]
@hedy881028 
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji :+1:，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
