### ISSUE TITLE
關於assignment左右兩邊type的規則

### ISSUE THREAD

**Issue by jeff0625** [compiler-f20/discussion#80]
助教好:
我想問有關assignment的左右兩邊type的允許原則是什麼，
我看測資裡面是boolean 跟real不行
那boolean跟integer是否可以?
還有若是a[1] = b[2] 這種array refference的是否也可以?

**Comment by chrisPyr** [comment]
@jeff0625 

Hi, 除了在spec中提到的限制外（e.g.  constant variable reference)，assignment 的規則就是兩邊type要一致，根據spec 中有關 assignment跟 type coercion的敘述：
1. Boolean 跟 real : 不行
2. a[1] = b[2] : 要看兩個array 的dimension 及 element type決定

**Comment by ran-ablaze** [comment]
補充一下
你說的部份都可以在readme中的
### Type Coercion and Comparison
找到

**Comment by jeff0625** [comment]
好的! 謝謝助教
