### ISSUE TITLE
Function Declaration 與 Function Definition

### ISSUE THREAD

**Issue by kaiiiz** [compiler-f20/discussion#81]
助教你們好：

請問這次作業需要考慮 Function Declaration 後出現相同 function name 的 Function Definition 的測資嗎？

因為 spec 好像沒有提到這件事，但是依照正常語言的規則，在進行 function definition 時應該要允許有提前宣告的 function declaration，而不是出現 symbol redeclaration，因此想確認一下這件事，感謝

另外，如果要考量這件事的話，參數的型別與回傳的型別是否也要同時進行檢查？

**Comment by chrisPyr** [comment]
@kaiiiz 

若spec跟測資中都沒有就無須考慮。
