### ISSUE TITLE
HW5 Invitations for this assignment have been disabled. 

### ISSUE THREAD

**Issue by forbis** [compiler-f20/discussion#85]
Hi TAs, I saw the mail said that hw5 will have PR today, so I just went to receive the assignment today but the system said "Invitations for this assignment have been disabled. "

Thank you.
<img width="459" alt="截圖 2020-12-29 下午8 57 07" src="https://user-images.githubusercontent.com/32932288/103285210-70f97800-4a18-11eb-8670-4ab26162ed53.png">

**Comment by ran-ablaze** [comment]
抱歉，助教在上傳sample code之後忘記重新把invitation打開了，現在已經把它打開。
