### ISSUE TITLE
hw5  ./activate_docker.sh 後的error

### ISSUE THREAD

**Issue by minyunh** [compiler-f20/discussion#86]
![螢幕快照 2021-01-03 下午02 02 04 上午](https://user-images.githubusercontent.com/66958434/103463535-0c1b8600-4d68-11eb-8ec3-5c3265557370.png)

 ./activate_docker.sh 後出現截圖上的資訊
目前有按照error給的網址
https://docs.docker.com/docker-for-mac/
還有網路上查到的方法去試，但是都沒有解決
https://cloud.tencent.com/developer/ask/38107
想問助教應該怎麼解決 謝謝～

**Comment by 5fe6eb50c7aa19f9** [comment]
@minyunh 
同學可以嘗試`sudo ./activate_docker.sh`看看。

**Comment by minyunh** [comment]
![螢幕快照 2021-01-03 下午12 26 19 下午](https://user-images.githubusercontent.com/66958434/103471761-eb324f80-4dbe-11eb-8b9c-3a7596f7a8a6.png)

用sudo ./activate_docker.sh 還是跳一樣的error

**Comment by chrisPyr** [comment]
@minyunh 

同學你先把preference的設定貼出來讓我們看一下

**Comment by minyunh** [comment]
![Uploading 螢幕快照 2021-01-03 下午12.37.59 下午.png…]()

**Comment by chrisPyr** [comment]
@minyunh 

同學你好，請參考這個
[issue](https://github.com/compiler-s20/discussion/issues/112)

照那位同學的方法將那行註解掉應該就可以了。
那行的用意是為了讓同學可以將usb掛在docker裡，才能做在開發板上，但是關於mac如何掛usb在docker中，我們也還找不到解決辦法。所以使用mac的同學請先用模擬器做作業就好，謝謝。

如果有其他同學找到如何在mac上掛usb的話也可以分享一下。

**Comment by minyunh** [comment]
助教您好
參考issue將line 83 註解掉後就可以執行  ./activate_docker.sh
但是會有bash: /home/student/.bashrc: Permission denied
make 以後會出現以下

![螢幕快照 2021-01-03 下午14 05 42 下午](https://user-images.githubusercontent.com/66958434/103472834-20de3500-4dcd-11eb-9fb4-d212fd4085bf.png)

**Comment by chrisPyr** [comment]
sudo也一樣嗎?

**Comment by minyunh** [comment]
用sudo就可以了！
感謝助教的幫忙～
