### ISSUE TITLE
無法accept作業問題

### ISSUE THREAD

**Issue by robincs07** [compiler-f20/discussion#89]
![image](https://user-images.githubusercontent.com/64472831/103612531-9b3ebe80-4f5f-11eb-8dca-2f04d361f293.png)

我在accept hw5的時候出現了上面有一個 Invitation for this assignment have been disabled
請問要如何解決

謝謝

**Comment by chrisPyr** [comment]
@robincs07 

同學你好，助教正在發patch先把作業關掉了，等發完patch就會開啟，大概5分鐘左右。
