### ISSUE TITLE
關於pull request

### ISSUE THREAD

**Issue by yyyipo** [compiler-f20/discussion#9]
助教好，
我執行了git pull後檢查了README.md檔，並且確認裡面安裝docker教學文的網址有被修改。
後來又改了student_info.ini檔裡的資料，make後再push回github上，卻發現README.md中我的資料確實修正了，但是安裝docker教學文的網址還是沒改變，而且pull request close 了。
想請問該如何解決?
謝謝助教！

**Comment by 5fe6eb50c7aa19f9** [comment]
@yyyipo 

這是正常的，
我們只有修正make前的README.md網址(用於教學)，
make後的README.md網址沒有修正，
你只要確保個人資料欄位正確即可。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji :+1:，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by chrisPyr** [comment]
＠yyyipo 

如果想要make後網址是正確的話，可以改動res/tmpl_readme.md 檔內的網址，這樣make後就會是正確的網址了。

"""
---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji :+1:，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
"""

**Comment by yyyipo** [comment]
好的，謝謝助教！
