### ISSUE TITLE
接收作業時檔案有缺失

### ISSUE THREAD

**Issue by denny3388** [compiler-f20/discussion#91]
如圖，我在接收作業之後發現 src 資料夾內好像少了很多檔案，請問我該如何解決 qq
![messageImage_1610265308685](https://user-images.githubusercontent.com/55589209/104117646-da08b600-535d-11eb-8fb9-11471332315a.jpg)

**Comment by ran-ablaze** [comment]
你的pull request還有一個尚未merge

**Comment by denny3388** [comment]
@ran-ablaze 助教您好，我有看過那個PR了，那個PR是兩個當中比較舊的那個，因為我已經merge了比較新的PR，所以舊的那個會發生conflict：
![2021-1-10 下午 07-17-21](https://user-images.githubusercontent.com/55589209/104121383-c28af680-5378-11eb-94f5-b9c2734cedb7.jpg)
所以我才沒有再次merge，請問我應該要merge嗎？

**Comment by ran-ablaze** [comment]
需要merge，因為sample都在裡面，你需要解決conflict，也就是conflict的地方保留PATCH 2 的資料

**Comment by denny3388** [comment]
@ran-ablaze 已經成功解決了！謝謝助教！
