### ISSUE TITLE
想請問期末考卷

### ISSUE THREAD

**Issue by 5ilianli** [compiler-f20/discussion#92]
助教好！<br/>
想請問期末成績和考卷大概何時會發放？<br/>
可以去拿答案卷嗎？<br/>
（因為放假回家，不知道是否需要回學校拿考卷）<br/>
<br/>
謝謝助教們，辛苦了。<br/>

**Comment by chrisPyr** [comment]
@5ilianli 
同學妳好，請參考 #93 。

**Comment by 5ilianli** [comment]
好的，謝謝助教的回覆。

**Comment by 5ilianli** [comment]
@chrisPyr
不好意思....想再請問助教一個問題，
如果之前缺席一次，想請問點名成績(5%)大概怎麼算？

（抱歉問這麼瑣碎的事 > < 因為赫然察覺到自己未點名一次 QQ，很擔心...）

**Comment by 5ilianli** [comment]
剛剛按錯回覆的地方了....
抱歉又重寄信給助教 > <

**Comment by chrisPyr** [comment]
@5ilianli 

關於期末總成績我們也不清楚老師最後會怎麼算分，所以沒辦法回答妳qq。

**Comment by 5ilianli** [comment]
謝謝助教得回覆，真的很感激！
